# SPDX-FileCopyrightText: 2025 portfiend
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: latheRecipe
  abstract: true
  id: BaseCarpetRecipe
  category: Carpet
  completetime: 1
  materials:
    Cloth: 100
