// SPDX-FileCopyrightText: 2024 DEATHB4DEFEAT <77995199+DEATHB4DEFEAT@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 sleepyyapril <123355664+sleepyyapril@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

using Content.Shared.Chemistry;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Chemistry.UI;

[GenerateTypedNameReferences]
public sealed partial class ReagentCardControl : Control
{
    public string StorageSlotId { get; }
    public Action<string>? OnPressed;
    public Action<string>? OnEjectButtonPressed;

    public ReagentCardControl(ReagentInventoryItem item)
    {
        RobustXamlLoader.Load(this);

        StorageSlotId = item.StorageSlotId;
        ColorPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = item.ReagentColor };
        ReagentNameLabel.Text = item.ReagentLabel;
        ReagentNameLabel.FontColorOverride = Color.White;
        FillLabel.Text = item.StoredAmount;
        EjectButtonIcon.Text = Loc.GetString("reagent-dispenser-window-eject-container-button");

        MainButton.OnPressed += args => OnPressed?.Invoke(StorageSlotId);
        EjectButton.OnPressed += args => OnEjectButtonPressed?.Invoke(StorageSlotId);
    }
}
