
using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._DEN.Job;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;


namespace Content.Client._DEN.Lobby.UI.Controls;

/// <summary>
///     A selection of job titles for this job.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class AlternateTitleSelectionMenu : FancyWindow
{
    public JobPrototype Job;
    public AlternateJobTitlePrototype AlternateJobTitle;
    public string? SelectedAlternateTitle;

    public event Action<string?>? SelectedAlternateTitleChanged;

    public AlternateTitleSelectionMenu(JobPrototype job,
        AlternateJobTitlePrototype titlesPrototype,
        string? selectedAlternateTitle = null)
    {
        RobustXamlLoader.Load(this);

        Job = job;
        AlternateJobTitle = titlesPrototype;

        var items = new List<ItemList.Item>();

        foreach (var title in titlesPrototype.Titles
            .Select(titleId => Loc.GetString(titleId)))
        {
            var titleItem = Titles.AddItem(title);

            if (title == selectedAlternateTitle)
                titleItem.Selected = true;

            items.Add(titleItem);
        }

        Titles.SetItems(items);
        Titles.OnItemSelected += OnItemSelected;
        Titles.OnItemDeselected += OnItemDeselected;
    }

    private void OnItemSelected(ItemList.ItemListSelectedEventArgs args)
    {
        var item = args.ItemList[args.ItemIndex];
        SelectedAlternateTitleChanged?.Invoke(item.Text);
    }

    private void OnItemDeselected(ItemList.ItemListDeselectedEventArgs args) =>
        SelectedAlternateTitleChanged?.Invoke(null);

}
