
using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._DEN.Job;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;


namespace Content.Client._DEN.Lobby.UI.Controls;

/// <summary>
///     A selection of job titles for this job.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class AlternateTitleSelectionMenu : FancyWindow
{
    public event Action<string?>? OnSelectedAlternateTitleChanged;

    public AlternateTitleSelectionMenu(JobPrototype job,
        AlternateJobTitlePrototype titlesPrototype,
        ISawmill sawmill,
        string? selectedAlternateTitle = null)
    {
        RobustXamlLoader.Load(this);

        var buttons = new List<LocId> { job.ID, };
        buttons.AddRange(titlesPrototype.Titles);

        foreach (var titleId in buttons)
        {
            sawmill.Info(titleId);
            var title = GetButtonText(job, titleId);

            if (selectedAlternateTitle != null && titleId == selectedAlternateTitle)
            {
                sawmill.Info($"Selected alternate title is: {selectedAlternateTitle}");
                continue;
            }

            var button = new Button
            {
                Text = title,
                MaxHeight = 30
            };

            button.OnPressed += _ => OnSelectedAlternateTitleChanged?.Invoke(titleId);
            TitlesContainer.AddChild(button);
            Titles.InvalidateMeasure();
        }
    }

    private string GetButtonText(JobPrototype job, string titleId) =>
        titleId == job.ID ? job.LocalizedName : Loc.GetString(titleId);
}
