using Content.Client.UserInterface.Controls;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.RichText;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;


namespace Content.Client._DEN.Lobby.UI.Controls;

[GenerateTypedNameReferences]
public sealed partial class LoadoutJobActionsWindow : FancyWindow
{
    public event Action<ProtoId<JobPrototype>>? OnToggleEditingActionPressed;

    private readonly JobPrototype _jobPrototype;

    public LoadoutJobActionsWindow(
        JobPrototype job)
    {
        RobustXamlLoader.Load(this);
        _jobPrototype = job;

        SetJobText();

        CopyTraitsAction.OnPressed += _ => OnCopyTraits();
        CopyLoadoutAction.OnPressed += _ => OnCopyLoadout();
        CopyBothAction.OnPressed += _ => OnCopyBoth();
        ToggleEditingAction.OnPressed += _ => OnToggleEditing();
        DeleteSavedLoadoutAction.OnPressed += _ => OnDeleteSavedLoadout();
    }

    private void SetJobText()
    {
        EditingLabel.Text = _jobPrototype.LocalizedName;
        LabelContainer.Visible = true;
    }

    private void OnCopyTraits()
    {
        // do something
    }

    private void OnCopyLoadout()
    {
        // do something
    }

    private void OnCopyBoth()
    {
        // do something
    }

    private void OnToggleEditing()
    {
        // this would probably be handled elsewhere
        OnToggleEditingActionPressed?.Invoke(_jobPrototype);
    }

    private void OnDeleteSavedLoadout()
    {
        // do something
    }
}
