// SPDX-FileCopyrightText: 2025 portfiend
//
// SPDX-License-Identifier: MPL-2.0

using Content.Client.Resources;
using Content.Shared.Clothing.Loadouts.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DEN.Lobby.UI.Controls;

/// <summary>
///     A container with a list of category buttons that are used to navigate between
///     tabs of the loadout UI.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class LoadoutCategoryList : BoxContainer
{
    [Dependency] private readonly IResourceCache _resourceCache = default!;

    private const string CategoryNameFontPath = "/Fonts/NotoSans/NotoSans-Bold.ttf";
    private const int CategoryNameFontSize = 16;
    private Font CategoryNameFont => _resourceCache.GetFont(CategoryNameFontPath, CategoryNameFontSize);

    /// <summary>
    ///     This represents the first leaf category in this list.
    ///     When this category list is opened, the leaf category will be automatically selected.
    /// </summary>
    public LoadoutCategoryPrototype? FirstLeafCategory;
    /// <summary>
    ///     This represents the first leaf category button in this list.
    ///     When this category list is opened, the leaf button will be automatically selected.
    /// </summary>
    public Button? FirstLeafButton;

    public LoadoutCategoryList()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        CategoryTitleLabel.FontOverride = CategoryNameFont;
    }

    /// <summary>
    ///     Sets the header text for this category.
    /// </summary>
    /// <param name="name">The header text to use.</param>
    public void SetLabelText(string name)
    {
        CategoryTitleLabel.Text = name;
    }
}
