// SPDX-FileCopyrightText: 2025 portfiend
//
// SPDX-License-Identifier: MPL-2.0


using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DEN.Lobby.UI.Controls;

/// <summary>
///     A button used to switch between loadout category panels.
///     "Leaf" category buttons use standard button styling; otherwise,
///     "branch" (non-leaf) category buttons point to a list of subcategories.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class LoadoutCategoryButton : Button
{
    private const string BranchButtonStyleClass = StyleNano.StyleClassAltButton;

    private bool _isLeaf = false;
    private string _labelText = string.Empty;
    private int _loadoutCount = 0;

    public LoadoutCategoryButton(bool leaf)
    {
        RobustXamlLoader.Load(this);

        _isLeaf = leaf;
        ToggleMode = _isLeaf;

        if (!_isLeaf)
            AddStyleClass(BranchButtonStyleClass);
    }

    /// <summary>
    ///     Sets the name text part of the loadout category.
    /// </summary>
    /// <param name="text">Label text to use.</param>
    public void SetLabelText(string text)
    {
        _labelText = text;
        UpdateLabel();
    }

    /// <summary>
    ///     Sets the number of currently-equipped loadouts for this category.
    /// </summary>
    /// <param name="count">The number of currently-equipped loadouts.</param>
    public void SetLoadoutCount(int count)
    {
        _loadoutCount = count;
        UpdateLabel();
    }

    private void UpdateLabel()
    {
        var text = _labelText;

        if (_loadoutCount != 0)
            text += $" ({_loadoutCount})";

        // TODO: Find a better way to denote branches/categories.
        if (!_isLeaf)
            text += " ...";

        Label.Text = text;
    }
}
