# SPDX-FileCopyrightText: 2022 Cheackraze
# SPDX-FileCopyrightText: 2022 OldDanceJacket
# SPDX-FileCopyrightText: 2022 Rane
# SPDX-FileCopyrightText: 2022 brainfood1183
# SPDX-FileCopyrightText: 2023 Adrian16199
# SPDX-FileCopyrightText: 2023 Carolyn3114
# SPDX-FileCopyrightText: 2023 Checkraze
# SPDX-FileCopyrightText: 2023 Colin-Tel
# SPDX-FileCopyrightText: 2023 Emisse
# SPDX-FileCopyrightText: 2023 Moony
# SPDX-FileCopyrightText: 2023 Scribbles0
# SPDX-FileCopyrightText: 2023 Ubaser
# SPDX-FileCopyrightText: 2023 deltanedas
# SPDX-FileCopyrightText: 2023 deltanedas <@deltanedas:kde.org>
# SPDX-FileCopyrightText: 2023 metalgearsloth
# SPDX-FileCopyrightText: 2024 Ed
# SPDX-FileCopyrightText: 2024 FoxxoTrystan
# SPDX-FileCopyrightText: 2024 Memeji
# SPDX-FileCopyrightText: 2024 SimpleStation14
# SPDX-FileCopyrightText: 2024 UnicornOnLSD
# SPDX-FileCopyrightText: 2024 Velcroboy
# SPDX-FileCopyrightText: 2024 flyingkarii
# SPDX-FileCopyrightText: 2024 rosieposie
# SPDX-FileCopyrightText: 2025 Ichaie
# SPDX-FileCopyrightText: 2025 Jonathan
# SPDX-FileCopyrightText: 2025 Plyush
# SPDX-FileCopyrightText: 2025 This_Is_Gray
# SPDX-FileCopyrightText: 2025 VMSolidus
# SPDX-FileCopyrightText: 2025 astriloqua
# SPDX-FileCopyrightText: 2025 juniwoofs
# SPDX-FileCopyrightText: 2025 juniwoofs <***>
# SPDX-FileCopyrightText: 2025 juniwoofs <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>
# SPDX-FileCopyrightText: 2025 sleepyyapril
# SPDX-FileCopyrightText: 2025 therealDLondon
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Arena
  - Asterisk
 # - Core - 02/22/24
  - Edge
  - Glacier
#  - Hammurabi - 02/22/24
#  - Lighthouse
#  - Saltern - commented pending rework
  - Shoukou
#  - Submarine
  - Tortuga
#  - TheHive - June 18th - pending rework
  - Baikal
  - Barrier
  - Gravel
#  - Gax - im so sorry this wasn't commented out
#  - Rad - im so sorry this wasn't commented out
#  - Meta
#  - Box
#  - Lambda - awaiting review
#  - Bagel - awaiting review
#  - Europa
