- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Arena
  - Asterisk
  - Core
  - Edge
  - Glacier
  - Hammurabi
  - Lighthouse
  - Pebble
#  - Saltern - commented pending rework
  - Shoukou
  - Submarine
  - Tortuga
  - TheHive
#  - Gax - im so sorry this wasn't commented out
#  - Rad - im so sorry this wasn't commented out
  - Meta
  - Box
#  - Lambda - awaiting review
#  - Bagel - awaiting review
#  - Europa
