// SPDX-FileCopyrightText: 2025 John Willis <143434770+CerberusWolfie@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 sleepyyapril <123355664+sleepyyapril@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

using Content.Shared.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

/// <summary>
/// ADAPTED FROM SECWATCH - DELTAV
/// </summary>

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class PsiWatchEntryControl : BoxContainer
{
    public PsiWatchEntryControl(PsiWatchEntry entry)
    {
        RobustXamlLoader.Load(this);

        Status.Text = Loc.GetString($"psionics-records-status-{entry.Status.ToString().ToLower()}");
        Title.Text = Loc.GetString("psi-watch-entry", ("name", entry.Name), ("job", entry.Job));

        Reason.Text = entry.Reason ?? Loc.GetString("psi-watch-no-reason");
    }
}
