// SPDX-FileCopyrightText: 2024 Skubman
// SPDX-FileCopyrightText: 2024 Tadeo
// SPDX-FileCopyrightText: 2025 BlitzTheSquishy
// SPDX-FileCopyrightText: 2025 Evaisa
// SPDX-FileCopyrightText: 2025 EvaisaDev
// SPDX-FileCopyrightText: 2025 Icepick
// SPDX-FileCopyrightText: 2025 corresp0nd
// SPDX-FileCopyrightText: 2025 taydeo
//
// SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

using Content.Shared._DV.CartridgeLoader.Cartridges;
using Content.Shared._DV.NanoChat;
using Content.Shared.Access.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DV.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NanoChatEntry : BoxContainer
{
    private const int MaxNameLength = 14;
    private const int MaxJobLength = 20;

    public event Action<uint>? OnPressed;
    private uint _number;
    private Action<EventArgs>? _pressHandler;

    public NanoChatEntry()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetRecipient(NanoChatRecipient recipient, uint number, bool isSelected)
    {
        // Remove old handler if it exists
        if (_pressHandler != null)
            ChatButton.OnPressed -= _pressHandler;

        _number = number;

        // Create and store new handler
        _pressHandler = _ => OnPressed?.Invoke(_number);
        ChatButton.OnPressed += _pressHandler;

        // Funky Station - Added "Unknown" fallback for name, was having weird issues when implementing group chats.
        NameLabel.Text = SharedNanoChatSystem.Truncate(recipient.Name ?? "Unknown", IdCardConsoleComponent.MaxFullNameLength);
        JobLabel.Text = SharedNanoChatSystem.Truncate(recipient.JobTitle ?? "", IdCardConsoleComponent.MaxJobTitleLength);
        JobLabel.Visible = !string.IsNullOrEmpty(recipient.JobTitle);
        UnreadIndicator.Visible = recipient.HasUnread;

        // Funky Station - Show group icon for group chats
        GroupIcon.Visible = recipient.IsGroup;

        ChatButton.ModulateSelfOverride = isSelected ? NanoChatMessageBubble.OwnMessageColor : null;
    }
}
