using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Content.Client.Message;
using Content.Client.UserInterface.Systems.Chat.Widgets;
using Robust.Client.Console;
using Robust.Shared.Timing;
using Robust.Client.UserInterface;
using Robust.Shared.Utility;


namespace Content.Client.UserInterface.Systems.Chat.Controls.Denu;

[GenerateTypedNameReferences]
public sealed partial class DenuWindow : AnimatedWindow
{
    private const string PreviewText = "\"Hello! *italic* **bold** ***bolditalic***\" *looks at you*";

    private readonly DenuUIController _denuUIController;
    private readonly ChatUIController _chatUIController;
    private IClientConsoleHost _consoleHost;

    public DenuWindow()
    {
        RobustXamlLoader.Load(this);

        _denuUIController = UserInterfaceManager.GetUIController<DenuUIController>();
        _chatUIController = UserInterfaceManager.GetUIController<ChatUIController>();
        _consoleHost = IoCManager.Resolve<IClientConsoleHost>();

        InitializeUI();
    }

    private void InitializeUI()
    {
        Title = "Denu";
        
        Tabs.SetTabTitle(0, "Chat");
        Tabs.SetTabTitle(1, "Help");

        HelpButton.Visible = true;
        HelpButton.Disabled = false;
        HelpButton.OnPressed += _ => Help();

        CloseButton.OnPressed += _ => Close();

        TypingToggleButton.WhileToggled += _denuUIController.ShowTypingIndicator;
        TypingToggleButton.OnToggledOff += _denuUIController.HideTypingIndicator;
        _consoleHost.AnyCommandExecuted += (_, _, _, _) => TypingToggleButton.Pressed = false;

        AutoFormatterCheckBox.OnToggled += e => _denuUIController.AutoFormatterEnabled = e.Pressed;
        RemoveAsterisksCheckBox.OnToggled += e => _denuUIController.RemoveAsterisks = e.Pressed;

        DialogueColorSelector.Color = _denuUIController.DialogueColor;
        DialogueColorSelector.OnColorChanged += color =>
        {
            _denuUIController.DialogueColor = color;
            UpdatePreview();
        };

        EmoteColorSelector.Color = _denuUIController.EmoteColor;
        EmoteColorSelector.OnColorChanged += color =>
        {
            _denuUIController.EmoteColor = color;
            UpdatePreview();
        };

        UpdatePreview();
    }

    void Help() { }

    private void UpdatePreview()
    {
        string dialogueColor = _denuUIController.DialogueColor.ToHex();
        string emoteColor = _denuUIController.EmoteColor.ToHex();
        
        string message = GetCurrentChatMessage();
        
        if (string.IsNullOrWhiteSpace(message))
        {
            message = MessageFormatter.Format(PreviewText);
            message = PreviewText + "\n" + message + "\n(Write a message in the chat input to see a preview)";
        }
        else
        {
            message =  MessageFormatter.Format(message, dialogueColor, emoteColor);
        }
        
        LivePreview.SetMarkup(message);
    }

    private string GetCurrentChatMessage()
    {
        var chatBox = UserInterfaceManager.ActiveScreen?.GetWidget<ChatBox>() ?? 
                     UserInterfaceManager.ActiveScreen?.GetWidget<ResizableChatBox>();
        
        return chatBox?.ChatInput?.Input?.Text ?? "Write a message in the chat input to see a preview.";
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        UpdatePreview();
        base.FrameUpdate(args);
    }
}
