# SPDX-FileCopyrightText: 2024 sleepyyapril
#
# SPDX-License-Identifier: MIT AND AGPL-3.0-or-later

- type: job
  id: CBURN
  name: job-name-cburn
  description: job-description-cburn
  playTimeTracker: JobERTCBURN
  setPreference: false
  startingGear: CBURNGear
  icon: "JobIconCBURN"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  special:
  - !type:AddImplantSpecial
    implants: [ CentCommImplant ]
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
