// SPDX-FileCopyrightText: 2025 DoctorJado
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._DEN.StationRecords;
using Content.Shared.Roles;
using Content.Shared.StationRecords;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;


namespace Content.Client._DEN.StationRecords;

[GenerateTypedNameReferences]
public sealed partial class StationJobsConsoleWindow : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    public event Action<string>? OnJobAdd;
    public event Action<string>? OnJobSubtract;

    public StationJobsConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void UpdateState(StationJobsConsoleState state)
    {
        if (state.JobList is null || state.JobSlots is null)
            return;

        PopulateJobsContainer(state.JobList, state.JobSlots);
        PopulateStationInfoContainer(state.JobList, state.JobSlots);
    }

    private void PopulateJobsContainer(IReadOnlyDictionary<string, uint?> jobList, IReadOnlyDictionary<string, uint?> jobSlots)
    {
        JobListing.RemoveAllChildren();
        foreach (var (job, amount) in jobList)
        {
            if (amount < 0 || amount is null)
                continue;

            if (!_prototype.TryIndex<JobPrototype>(job, out var jobProto) && jobProto is null
                || !jobProto.OverrideConsoleVisibility.GetValueOrDefault(jobProto.SetPreference))
                continue;

            var totalSlots = jobSlots.FirstOrDefault(a => a.Key == job).Value;

            var jobEntry = new StationJobsConsoleJobRow(jobProto)
            {
                JobName = { Text = jobProto.LocalizedName },
                JobAmount = { Text = amount.ToString() },
                JobSlots = { Text = $"({totalSlots})" },
                IncreaseJobSlot = { Disabled = !jobProto.AdjustableCount},
                DecreaseJobSlot = { Disabled = !jobProto.AdjustableCount}
            };

            jobEntry.DecreaseJobSlot.OnPressed += (args) => { OnJobSubtract?.Invoke(job); };
            jobEntry.IncreaseJobSlot.OnPressed += (args) => { OnJobAdd?.Invoke(job); };
            JobListing.AddChild(jobEntry);
        }
    }

    private void PopulateStationInfoContainer(IReadOnlyDictionary<string, uint?> jobList, IReadOnlyDictionary<string, uint?> jobSlots)
    {

        var totalSlots = jobSlots.Values.Sum(u => u ?? 0);
        var openSlots = jobList.Values.Sum(u => u ?? 0);
        var totalCrew =  totalSlots - openSlots;

        TotalSlotsLabel.Text = Loc.GetString("jobs-console-job-capacity", ("num", totalSlots));
        TotalCrewLabel.Text = Loc.GetString("jobs-console-current-crew", ("num", totalCrew));
        TotalOpenSlotsLabel.Text = Loc.GetString("jobs-console-open-jobs", ("num", openSlots));
    }
}
