using System.Numerics;
using Content.Shared.Roles;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Prototypes;


namespace Content.Client._DEN.StationRecords;


[GenerateTypedNameReferences]
public sealed partial class StationJobsConsoleJobRow : PanelContainer
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    public StationJobsConsoleJobRow(JobPrototype jobProto)
    {
        RobustXamlLoader.Load(this);

        Initialize(jobProto);
    }

    private void Initialize(JobPrototype jobProto)
    {
        IoCManager.InjectDependencies(this);

        JobIcon.Texture = _prototypeManager.Index(jobProto.Icon).Icon.Frame0();
    }
}

