// SPDX-FileCopyrightText: 2025 Mnemotechnican
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.UserInterface.Controls;
using Content.Shared.FloofStation.Info;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;


namespace Content.Client._Floof.Info;


[GenerateTypedNameReferences]
public sealed partial class NsfwDisclaimerWindow : FancyWindow
{
    private bool? _accepted;

    public NsfwDisclaimerWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        AcceptButton.OnPressed += _ =>
        {
            _accepted = true;
            SendResponse();
        };
        DeclineButton.OnPressed += _ =>
        {
            _accepted = false;
            SendResponse();
        };
    }

    public void OnWindowClosed()
    {
        // No more escape to ignore
        if (!_accepted.HasValue)
            SendResponse();
    }

    public void SendResponse()
    {
        var ev = new PopupDisclaimerResponseMessage();
        ev.Response = _accepted ?? false;

        Close();
    }
}

