// SPDX-FileCopyrightText: 2025 Mnemotechnican
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Floof.Examine;
using Microsoft.CodeAnalysis.Differencing;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;


namespace Content.Client._Floof.Examine;


[GenerateTypedNameReferences]
public sealed partial class CustomExamineSettingsWindow : FancyWindow
{
    public event Action<List<CustomExamineData>>? OnSave;

    private Dictionary<Guid, CustomExamineEntry> _customExamineData;

    public CustomExamineSettingsWindow()
    {
        RobustXamlLoader.Load(this);

        _customExamineData = new();

        EditWindow.ExamineControl.MaxContentLength = 256;

        CreateNewButton.OnPressed += _ => CreateNewExamine(_customExamineData.Count);
    }

    private void PopulateExamineEntries(List<CustomExamineData> data)
    {
        for (var i = 0; i < data.Count; i++)
        {
            var examine = data[i];
            examine.Updated = false;
            CreateNewExamine(i, examine);
        }
    }

    private void RefreshEntries()
    {
        PopulateExamineEntries(_customExamineData.Values.Select(e => e.ExamineData).ToList());
    }

    private void CreateNewExamine(int index, CustomExamineData? data = null)
    {
        if (_customExamineData.Count >= 5)
            return;

        var container = new BoxContainer();
        container.HorizontalExpand = true;
        container.SetHeight = 30f;
        container.Margin = new(1);

        var entry = new CustomExamineEntry();
        var defaultData = data ?? GetDefaultExamineData();
        var identifier = Guid.NewGuid();

        entry.SetIdentifier(identifier);
        entry.SetData(defaultData);

        entry.TitleLabel.Text = $"Entry #{index + 1}";
        entry.EditButton.OnPressed += _ => EditExamine(identifier);
        entry.DeleteButton.OnPressed += _ => DeleteExamine(identifier);

        _customExamineData.Add(identifier, entry);
        container.AddChild(entry);
        ExamineContainer.AddChild(container);
    }

    private void EditExamine(Guid identifier)
    {
        if (!_customExamineData.TryGetValue(identifier, out var entry))
        {
            EditWindow.Visible = false;
            return;
        }

        EditWindow.EditingLabel.Text =
            Loc.GetString("custom-examine-editing", ("entry", entry.TitleLabel.Text?.ToLower() ?? string.Empty));
        EditWindow.Visible = true;
        EditWindow.ExamineControl.SetData(entry.ExamineData);

        EditWindow.SaveButton.OnPressed += _ =>
        {
            if (!_customExamineData.ContainsKey(entry.Identifier))
                return;

            var data = EditWindow.ExamineControl.GetData();
            data.Updated = true;

            GuidelinesText.Text = data.Content;
            _customExamineData[entry.Identifier].SetData(data);
            OnSave?.Invoke(_customExamineData.Values.Select(e => e.ExamineData).ToList());
        };

        EditWindow.ResetButton.OnPressed += _ =>
        {
            var data = GetDefaultExamineData();
            data.Updated = true;

            _customExamineData[entry.Identifier].SetData(data);
            EditWindow.ExamineControl.SetData(data, true);
            OnSave?.Invoke(_customExamineData.Values.Select(e => e.ExamineData).ToList());
        };
    }

    private void DeleteExamine(Guid identifier)
    {
        if (!_customExamineData.TryGetValue(identifier, out var entry))
        {
            EditWindow.Visible = false;
            return;
        }

        _customExamineData.Remove(entry.Identifier);
        RefreshEntries();
    }

    private CustomExamineData GetDefaultExamineData() =>
        new()
        {
            Content = null,
            VisibilityRange = 2,
            ExpireTime = TimeSpan.Zero,
            RequiresConsent = false,
            LastUpdate = TimeSpan.Zero
        };

    public void SetData(List<CustomExamineData> data, bool force = false)
    {
        PopulateExamineEntries(data);
    }
}

