// SPDX-FileCopyrightText: 2025 Mnemotechnican
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared._Floof.Examine;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Floof.Examine;


[GenerateTypedNameReferences]
public sealed partial class CustomExamineEntry : BoxContainer
{
    public Guid Identifier;
    public CustomExamineData ExamineData;

    public CustomExamineEntry()
    {
        RobustXamlLoader.Load(this);
    }
    
    public void SetIdentifier(Guid identifier) => Identifier = identifier;

    public void SetData(CustomExamineData data) => ExamineData = data;

    public CustomExamineData GetData() => ExamineData;
}

