// SPDX-FileCopyrightText: 2025 Mnemotechnican
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;


namespace Content.Client._Floof.Examine;


[GenerateTypedNameReferences]
public sealed partial class CustomExaminePartEditWindow : BoxContainer
{
    public CustomExaminePartEditWindow()
    {
        RobustXamlLoader.Load(this);
    }
}

