
using Content.Client.Message;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._DEN.Lobby.UI.FlavorText;

[GenerateTypedNameReferences]
public sealed partial class FlavorTextEntry : BoxContainer
{
    public Action<string>? OnFlavorTextChanged;

    public FlavorTextEntry()
    {
        RobustXamlLoader.Load(this);

        FlavorInput.OnTextChanged += args =>
        {
            var text = Rope.Collapse(args.TextRope).Trim();
            OnFlavorTextChanged?.Invoke(text);
        };
    }

    public void SetTitle(string title)
    {
        FlavorTitle.SetMarkup($"[head=2]{title}[/head]");
        FlavorTitle.Visible = !string.IsNullOrWhiteSpace(title);
    }

    public void SetDescription(string description)
    {
        FlavorDescription.SetMarkup(description);
        FlavorDescription.Visible = !string.IsNullOrWhiteSpace(description);
    }

    public void SetPlaceholder(string placeholder)
    {
        var node = new Rope.Leaf(placeholder);
        FlavorInput.Placeholder = node;
    }

    public void SetInputText(string value)
    {
        var node = new Rope.Leaf(value);
        FlavorInput.TextRope = node;
    }
}
