using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DEN.Paint.UI;

[GenerateTypedNameReferences]
public sealed partial class MagicPaintWindow : DefaultWindow
{
    /// <summary>
    /// Invoked when the user selects a new color.
    /// </summary>
    public Action<Color>? OnColorChanged;

    private StyleBoxFlat _styleBox;

    public MagicPaintWindow()
    {
        RobustXamlLoader.Load(this);

        _styleBox = new();
        PreviewColor.PanelOverride = _styleBox;

        ColorSelector.OnColorChanged += color =>
        {
            OnColorChanged?.Invoke(color);
            UpdatePreview();
        };
    }

    public void SetColor(Color color)
    {
        ColorSelector.Color = color;
        UpdatePreview();
    }

    private void UpdatePreview()
    {
        _styleBox.BackgroundColor = ColorSelector.Color;
    }
}
