using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared.Chemistry.Reaction;
using Content.Shared.Chemistry.Reagent;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._DEN.RecipeFinder.UI;

[GenerateTypedNameReferences]
public sealed partial class BartenderRecipeFinderWindow : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = null!;
    [Dependency] private readonly IComponentFactory _componentFactory = null!;

    private readonly ProtoId<ReagentPrototype> _bloodReagent = "Blood";
    private List<ProtoId<ReagentPrototype>> _bloodDrinks = new();

    public BartenderRecipeFinderWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        PopulateCacheLists();
    }

    private void PopulateCacheLists()
    {
        foreach (var reactionPrototype in _prototypeManager.EnumeratePrototypes<ReactionPrototype>())
        {
            if (!reactionPrototype.Reactants.ContainsKey(_bloodReagent) &&
                !reactionPrototype.Reactants.Any(r => _bloodDrinks.Contains(r.Key)))
                continue;

            foreach (var productId in reactionPrototype.Reactants.Keys)
                _bloodDrinks.Add(productId);
        }
    }

    private bool IsNsfw(ProtoId<ReagentPrototype> reagentId)
    {
        return _prototypeManager.TryIndex(reagentId, out var reagentPrototype) && reagentPrototype.NoRandom;
    }

    private bool ContainsBlood(ProtoId<ReagentPrototype> reagentId)
    {
        return _bloodDrinks.Contains(reagentId);
    }
}
