- type: entity
  name: blue pumpkin
  parent: FoodProduceBase
  id: FoodBluePumpkin
  description: A large, blue... berry. Seriously.
  components:
  - type: Item
    size: Small
  - type: FlavorProfile
    flavors:
      - bluepumpkin
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 25
        reagents:
        - ReagentId: Ammonia
          Quantity: 10
        - ReagentId: Chlorine
          Quantity: 5
        - ReagentId: Vitamin
          Quantity: 10
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: JuiceBluePumpkin
        Quantity: 10
  - type: Sprite
    sprite: Floof/Objects/Specific/Hydroponics/blue_pumpkin.rsi
  - type: Produce
    seedId: bluePumpkin
  - type: Damageable
    damageContainer: Biological
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 16
      behaviors:
      - !type:PlaySoundBehavior
        sound:
          collection: desecration
      - !type:SpillBehavior
        solution: food
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
  - type: Tag
    tags:
    - Fruit