- type: entity
  abstract: true
  parent: FoodBowlBase
  id: FoodBowlSaladBase
  components:
  - type: Food
    utensil: Fork

- type: entity
  abstract: true
  parent: FoodBowlBase
  id: FoodBowlNoodlesBase
  components:
  - type: Food
    utensil:
    - Fork
    - Spoon
